### ISSUE TITLE
[BUG] Mod works on vanilla servers

### ISSUE THREAD

**Issue by VidTu** [Alpvax/GoProne#10]
The mod works on vanilla servers, this is cheat-like behavior, and players can be punished for this.

**Comment by Alpvax** [comment]
I think you only look prone on the client, no-one else will see you prone.
I will definitely look into it however, as it could be used to look under blocks that other players could not (without a piston/trapdoor etc.).

**Comment by VidTu** [comment]
Yeah, you look prone on client only. But some servers (1.12.2 + ViaVersion in my case) do not check collision for non solid blocks. (i.e. you can go prone under glass or slab)

EDIT: 1.14+ servers check for collision more strictly, but there are some bypasses using doors and gates. This can be solved by sending prone (keybind) packet to server without changing the pose. If mod exists severside, it responses with "pose changing" packet.

**Comment by Alpvax** [comment]
Fixed in the latest version (1.17.1-1.4.1)

Mod is now entirely disabled on a vanilla server (technically the client "toggle state" can be changed, but it has no effect on a vanilla server).
