### ISSUE TITLE
Mod goprone uses the version unknown which isn't compatible with Loader's extended semantic version format

### ISSUE THREAD

**Issue by Kino0208** [Alpvax/GoProne#13]
Loading Minecraft 1.18.2 with Fabric Loader 0.14.8

Mod goprone uses the version unknown which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'unknown'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version

**Comment by Alpvax** [comment]
I will look into the issue, but currently this is a Forge mod. The fabric stuff is still very much WIP.
If possible, could you please send a log file for more information, and let me know what your setup is (i.e. client type: vanilla, fabric or forge, server type: vanilla, fabric, forge or singleplayer).

**Comment by Kino0208** [comment]
sure Although they may have little impact on performance or stability（machine translation）
[2022-06-21-5.log](https://github.com/Alpvax/GoProne/files/8972989/2022-06-21-5.log)

**Comment by Alpvax** [comment]
Fixed by #14
