### ISSUE TITLE
[1.19-Forge] Not going to prone when keybind is set on mouse buttons.

### ISSUE THREAD

**Issue by Gbergz** [Alpvax/GoProne#15]
Title^

Keybind only works if on a keyboard bind.
In 1.18 and previous versions this wasn't an issue.

**-** Gbergz

**Comment by Alpvax** [comment]
Sorry, it was an oversight when I redesigned it, I assumed that everyone would be using a keyboard key.
I will fix it ASAP.

**Comment by Alpvax** [comment]
Should be fixed by fe3e44cef5e57286c8ed5661a6b2aeebd8a190e6
