### ISSUE TITLE
[1.19.3] Crash when entering boats 

### ISSUE THREAD

**Issue by ffuentesm** [Alpvax/GoProne#16]
![image](https://user-images.githubusercontent.com/44974827/210560497-a7039c59-c201-4eb5-a4d8-4ec196345064.png)
GoProne: GoProne 1.19-2.0.4
Log: https://crashy.net/dkVJv3EJ23vBCVar3ylm
Even if the 1.19.2 version of Goprone works in 1.19.3, there are a few crashes when taking some actions.

**Comment by Alpvax** [comment]
Looks like the obfuscation changed, so the mod will not work in 1.19.3. I should be able to update it soon.
