### ISSUE TITLE
Incompatibility with Incapacitated

### ISSUE THREAD

**Issue by kawaiicakes** [Alpvax/GoProne#19]
**Minecraft 1.19.2**
**Forge Mod Loader 43.2.14**
**GoProne 1.19-2.0.4, Incapacitated 1.4.4.1**

Several unexpected behaviors arise when using these two mods together. I suspect it's due to how Incapacitated handles how the player can/can't move while incapacitated. Some of the issues are as follows:

- The toggle prone key does not work, and if used, prevents the player from proning until the game is restarted.
- The normal prone behaviour does not work; instead the player must stand still when holding **c** otherwise the player will simply glitch from a prone to non-prone position and then continue moving in the direction they were moving. If the player continues holding c at this point, they will finally go into prone while crawling, but pressing/releasing any movement key will cancel this.
- If the player prones while standing still, they will not be able to use the movement keys otherwise the prone will be cancelled. 

No relevant logs were produced. Please let me know if any more info or testing is required from me.
Thanks for your time.

**Comment by CartoonishVillain** [comment]
Bug is almost certainly on Incapacitated's end, I think. I believe I end up setting the forced position to null every tick while not down which would explain the bug if true (preliminary investigation, just following off of context I saw on github, didn't check if this was actually in a tick loop)
