### ISSUE TITLE
wrong requirement

### ISSUE THREAD

**Issue by LordGriefington** [Alpvax/GoProne#20]
it tells me fabric loader 0.12.21 is missing
![gopronefabric](https://github.com/Alpvax/GoProne/assets/83673600/419d6702-e809-4132-848c-77f6c34f226f)
I am using minecraft 1.20.1, fabric loader 0.12.21, fabric-api-0.86.0

**Comment by Alpvax** [comment]
It says that you need fabric loader 0.14.21. If you have 0.12.21, that is the incorrect version, according to https://fabricmc.net/2023/05/25/120.html

**Comment by LordGriefington** [comment]
my apologies, I don't know how this could happen. I am using fabric 0.14.21. the mentioned fabric 0.12.21 doesn't even exist, at least not public.
![fabric](https://github.com/Alpvax/GoProne/assets/83673600/465edacb-8c54-458f-992d-7d86b78210a5)
you may need this 
[log.txt](https://github.com/Alpvax/GoProne/files/12178245/log.txt)

**Comment by LordGriefington** [comment]
netherdeeps works fine in game. I get the same when I remove it. I don't use optifine, I had it the past and I keep it unchecked. I just updated to jdk-18 still the same. does it look for a mod fabrc 0.14.21 instead of the loader? all other mods are working fine. has someone else that problem?
