### ISSUE TITLE
version change request

### ISSUE THREAD

**Issue by Worgrick** [Alpvax/GoProne#7]
I was wondering if you could add a version for 1.12. I get that is before the update, but I'm using a mod iod, that lets you do that plus there are alot of people still on that version. I'm just making a request/suggestion.

**Comment by Alpvax** [comment]
Unfortunately, the way Ido implements the feature means that I can't hook into it. I would have to do a lot of work to make it work, and even then it would not be very good.
Add to that the fact that 1.12 is almost 3 years old, and no longer supported by the forge team, and it is just more effort than I am willing to spend on such an old version. Sorry.
